### ISSUE TITLE
Step fails due to Bundler on 11.2 stack

### ISSUE THREAD

**Issue by AaronSofaer-PGE** [bitrise-steplib/steps-ios-auto-provision#108]
When running the step on the Xcode 11.2 stack, the following error presents itself:

> ERROR:  Error installing bundler:
> 	"bundle" from bundler conflicts with /Users/vagrant/.rbenv/versions/2.6.5/bin/bundle

This is due to the change that was merged 4 hours ago in https://github.com/bitrise-steplib/steps-ios-auto-provision/pull/107 and has also been commented on in https://github.com/bitrise-steplib/steps-ios-auto-provision/pull/107#issuecomment-574767349 .

**Comment by cathyharmon** [comment]
Hello,

We are currently working to correct this issue.  Until it is fixed, please try the following workaround:

- Use the 1.5.0 version of the iOS Auto Provision step (you can select this as an input to the step in the workflow editor)

- Add a script step prior to the iOS Auto Provision step to install bundler 1.17.3. The script step should have 'gem install bundler --force -v 1.17.3`

**Comment by godrei** [comment]
Hi @AaronSofaer-PGE ,
thanks for the issue report, we released a new version [1.5.2,](https://github.com/bitrise-steplib/steps-ios-auto-provision/releases/tag/1.5.2) which fixes the issue.
I'll close this issue, but if you still experience the problem please open a new issue!
