### ISSUE TITLE
Error: Developer Portal Authentication

### ISSUE THREAD

**Issue by Vanclief** [bitrise-steplib/steps-ios-auto-provision#110]
I am experiencing the following error:
```
Developer Portal authentication
Error:
developer portal apple id not provided for this build
Stacktrace (for debugging):
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise663306743/step_src/lib/autoprovision/auth_data.rb:21:in `validate'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise663306743/step_src/lib/autoprovision/auth_helper.rb:21:in `login'
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise663306743/step_src/step.rb:25:in `<main>'
```

Which should be related to this line:

https://github.com/bitrise-steplib/steps-ios-auto-provision/blob/master/lib/autoprovision/auth_data.rb#L21

From where is `apple_id` being read? I have connected my Apple Account to Bitrise, as well attempted to create both secret and env variables with the name `APPLE_ID`

**Comment by Vanclief** [comment]
This is not an issue in the code, all that was required was to add on Bitrise the Apple ID under the Application Team.

**Comment by non-binary** [comment]
Hi @Vanclief,

Great to hear you were able to fix your issue.

Please don't hesitate to reach out again if you have any other questions.

Thanks,
Luna

**Comment by lordkiz** [comment]
@non-binary @Vanclief  I am having same issues. Where can I find this Application Team section? Is it the same as Team?

**Comment by bitce** [comment]
hi @lordkiz, you can find the step-by-step guide here:https://devcenter.bitrise.io/getting-started/connecting-apple-dev-account/#enabling-apple-developer-portal-integration
