### ISSUE TITLE
Support Mac Catalyst apps

### ISSUE THREAD

**Issue by MortenGregersen** [bitrise-steplib/steps-ios-auto-provision#119]
Right now this step only creates iOS provisioning profiles. With Mac Catalyst it should be able to create provisioning profiles for macOS (Catalyst).

I have no idea how the step should be changed to accommodate this, but hope that someone has.

**Comment by non-binary** [comment]
Hi @MortenGregersen,

The current version of the step is not able to manage macOS codesigning files. We have an investigation task in our backlog to fully revise the Catalyst support. We will let you know once this has been completed.

**Comment by MortenGregersen** [comment]
It is still important to me. I Think @non-binary should answer (if they still work for Bitrise).

**Comment by mefiblogger** [comment]
Hello,

It's Mefi here from the Bitrise CoreSteps Team. Thanks for reaching out helping us and the mobile community to have a better experience with Bitrise steps. 💜

We started to have a broader review of all the open issues and PRs and we are continuously prioritizing these in our sprints.

We reviewed this issue and we found it to be a valid feature request. As this step is explicitly for iOS auto provisioning, we plan to create a new step regarding the macOS auto provision process. We are collecting new feature requests on our [Discuss forum](https://discuss.bitrise.io/c/feature-request/) where you can upvote and discuss further details. As this one is on our current roadmap, I close the issue and we'll share an update once we released the new version of the step. Until then, feel free to create a feature request and share your thoughts on Discuss.

Happy building! 🚀
