### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by yonaskolb** [bitrise-steplib/steps-ios-auto-provision#124]
Getting sporadic errors saying `You are not allowed to access the document you requested`

Seems related to this Fastlane issue https://github.com/fastlane/fastlane/issues/16430

**Comment by ecamacho** [comment]
@yonaskolb [My PR](https://github.com/fastlane/fastlane/pull/16478) to fix this issue was merged. Please, give it a try and let me know if it works for you.
