### ISSUE TITLE
New GUI Apple portal - developer portal apple id not provided for this build

### ISSUE THREAD

**Issue by rachid-debu** [bitrise-steplib/steps-ios-auto-provision#126]
Hello

I face an error while trying to auto provision.

`developer portal apple id not provided for this build`

I have setup everything (I think).
Here are screens of what I've setup so far.

<img width="1643" alt="api-apple-3" src="https://user-images.githubusercontent.com/17178180/83883325-a0c2f480-a743-11ea-90fc-93442a996916.png">

![api-apple-2](https://user-images.githubusercontent.com/17178180/83883341-a3bde500-a743-11ea-8423-244d12a492eb.png)

![api-apple-1](https://user-images.githubusercontent.com/17178180/83883343-a4567b80-a743-11ea-8c30-a7d7afaa65fa.png)

Since the GUI has changed, maybe there's something else that has to be done. Need help please

**Comment by non-binary** [comment]
Hi @rachid-debu,

Can you please share a build link so I can look at your workflows? Please ensure support access is enabled (by going to project settings).

**Comment by bitce** [comment]
Hi @rachid-debu! The issue here is that you are using version 1.x.x of the step. The new method of authentication is introduced in 2.x.x and only available from that version and the new ones going forward. Please update the version and let us know how it goes!

**Comment by rachid-debu** [comment]
hi, thanks for answer

@non-binary example of build that fails: https://app.bitrise.io/build/c5ca24dc79298507 

@bitce version 1.x.x of step iOS Auto provision (this is the one that fails) ? I can't see a 2.x.x version of that step (screen 1). I can see that another provision step exists (screen 2), but version do not match. 

![Capture d’écran 2020-06-08 à 13 59 49](https://user-images.githubusercontent.com/17178180/84028186-947fa700-a990-11ea-93a0-82ce4df3d822.png)

**Comment by bitce** [comment]
Sorry for the confusion, the step was indeed released as a new step. You need to use the iOS Auto Provision step with App Store Connect API. The original step still uses the old method.

**Comment by rachid-debu** [comment]
Thanks. OK i'm using the `iOS Auto Provision step with App Store Connect API` now.

Can it be ran if I'm building the APP with a `Scripts` step ? I mean, my build is successful, but the provision is not. Looks like he can't find some variables. 

`Failed to analyze project: failed to find the main target of the scheme (Doyouno): failed to find scheme (Doyouno) in project: scheme Doyouno not found in Doyouno`

https://app.bitrise.io/build/1717dca025d9baad#?tab=log

I'm really stuck.. Company needs the iOS build to work in order for us to continue using bitrise. And I would really want to, it'd save me lots of time building..

**Comment by kndl22** [comment]
Hi,
I have the same issue:
`developer portal apple id not provided for this build`

I'm using the iOS Auto Provision with Apple ID step version 1.5.3.

I've connected apple developer portal account at the team tab.

**Comment by non-binary** [comment]
Hi @kndl22,

Can you please send a link to a build?

**Comment by kndl22** [comment]
Hi,
@non-binary here's he link: https://app.bitrise.io/build/c364f53088f01def#?tab=log

**Comment by non-binary** [comment]
Your team tab shows that no account is connected. Please correct this by signing in over on the settings page and enabling it again.

![Screen Shot 2020-07-07 at 7 24 39 AM](https://user-images.githubusercontent.com/6799989/86772934-f3cde700-c022-11ea-9d3e-0db807b23659.png)

**Comment by kndl22** [comment]
It shows my name attached there:

<img width="1752" alt="Screen Shot 2020-07-07 at 14 28 01" src="https://user-images.githubusercontent.com/6260759/86773395-4d073c00-c05e-11ea-9d78-ad791028ced5.png">

**Comment by bitce** [comment]
Hi @kndl22,

As described above in the thread, there are two separate steps by now. 

The issue is that you are using the deprecated step, but have connected your account through the new API key method. You either have to use the new App Store Connect API step, or connect your account with the deprecated method.

**Comment by kndl22** [comment]
Hi @bitce,
Thanks for being responsive.
The only step regarding provisioning i see in the list is iOS Auto Provision with Apple ID. 
"iOS Auto Provision step with App Store Connect API" doesn't exist in the list.

**Comment by bitce** [comment]
I see, thanks. Can you send us a screenshot of you searching for the step but it not appearing?

**Comment by kndl22** [comment]
Found it,
Had to change from the "Flutter" sign at the top to "All" and that did the magic.

I'm attaching screenshot in case someone else getting here because of this:
<img width="839" alt="Screen Shot 2020-07-08 at 14 40 08" src="https://user-images.githubusercontent.com/6260759/86914833-a0928c00-c129-11ea-8ee9-1373f303a266.png">
<img width="844" alt="Screen Shot 2020-07-08 at 14 34 17" src="https://user-images.githubusercontent.com/6260759/86914839-a2f4e600-c129-11ea-830f-1943bb3fb8d8.png">

Right now I'm facing other build error:
`Failed to register device: json: cannot unmarshal object into Go struct field DevicesResponse.data of type []appstoreconnect.Device`

But this is irrelevant for this topic.

**Comment by bitce** [comment]
Thanks @kndl22! I've created a task to make the step appear as we'd expect to, and be sure to reach out to us about this latest error too, I believe it's an issue with the step we're looking at already.

**Comment by jposes22** [comment]
Same issue here with native project please fix it we cant sign projects!

**Comment by bitce** [comment]
Hi @jposes22,

Are you referring to the original error reported in the thread? If so, the answer is above, there are two steps with two different authentication methods. Make sure yours match!

**Comment by rachid-debu** [comment]
Hi, didn't follow this thread for a while. 

@bitce in fact, this very step `steps-ios-auto-provision` never worked for me either.

So i'm using the deprecated method `steps-ios-auto-provision-appstoreconnect` from https://github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect 

I need to try again with `steps-ios-auto-provision` but I don't have much time for this (since the older is working, we are using it, it's fine).

@bitce feel free to close this issue. I won't close it because I fixed the issue by using another repo, so..

**Comment by bitce** [comment]
I see! I believe we discussed this, I was curious about @jposes22 specifically. It is the other way around though, `steps-ios-auto-provision-appstoreconnect` is the new version and the legacy one is the `steps-ios-auto-provision`.
