### ISSUE TITLE
Auto provision step fails due to new Xcode object version. 

### ISSUE THREAD

**Issue by matthewc13** [bitrise-steplib/steps-ios-auto-provision#132]
Need to add support for Xcode 12s new object version. 

Trying auto provisioning with this results in.
```
Error:
[Xcodeproj] Unknown object version. 
``` 

XCode proj has been updated with this newest version 
https://github.com/CocoaPods/Xcodeproj

**Comment by vfxdrummer** [comment]
This is hitting us as well. Any update on this issue?

**Comment by vfxdrummer** [comment]
Added this PR to update xcodeproj to latest version, 1.18.0.
I *think* that should do it. 🤷

**Comment by matthewc13** [comment]
https://github.com/bitrise-steplib/steps-ios-auto-provision/pull/134 merged now we just need a release.

**Comment by vfxdrummer** [comment]
Nice! any ETA on release?

**Comment by parrots** [comment]
This just started breaking for me overnight, despite being on Xcode 12 stack for months (and also having an App Clip, which I believe triggers this bug). Why would this be a new break for me, and what can be done to work around it until a release?

**Comment by matthewc13** [comment]
Closing as this is fixed as of https://github.com/bitrise-steplib/steps-ios-auto-provision/releases/tag/1.5.4
