### ISSUE TITLE
undefined method `icloud'

### ISSUE THREAD

**Issue by rickmanelius** [bitrise-steplib/steps-ios-auto-provision#136]
We are getting the following error during the `ios-auto-provision` step (current version v1.5.3).

```
Ensure Provisioning Profiles on Developer Portal
checking app for target: ContactMapping (com.contactmapping.mobile) on developer portal
Push Notifications already enabled
set CloudKit: on
set iCloud: on
Error:
undefined method `icloud' for Spaceship::Portal::AppService:Class
Did you mean?  cloud
Stacktrace (for debugging):
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise794133273/step_src/lib/autoprovision/portal/app_client.rb:192:in `sync_app_services'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise794133273/step_src/lib/autoprovision/profile_helper.rb:90:in `block in ensure_manual_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise794133273/step_src/lib/autoprovision/profile_helper.rb:81:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise794133273/step_src/lib/autoprovision/profile_helper.rb:81:in `ensure_manual_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise794133273/step_src/lib/autoprovision/profile_helper.rb:42:in `block in ensure_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise794133273/step_src/lib/autoprovision/profile_helper.rb:38:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise794133273/step_src/lib/autoprovision/profile_helper.rb:38:in `ensure_profiles'
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise794133273/step_src/step.rb:90:in `<main>'
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | ios-auto-provision (exit code: 1)                             | 42.12 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...github.com/bitrise-steplib/steps-ios-auto-provision/issues |
| Source: https://github.com/bitrise-steplib/steps-ios-auto-provision          |
+---+---------------------------------------------------------------+----------+
```

I wanted to confirm that the iCloud key was in fact valid. So [here is where it's called in this step](https://github.com/bitrise-steplib/steps-ios-auto-provision/blob/1.5.3/lib/autoprovision/portal/app_client.rb#L192). Specifically:

```
        else
          Log.success('set CloudKit: on')
          app = app.update_service(Spaceship::Portal.app_service.cloud_kit.cloud_kit)
        end

        if app_features['iCloud']
          Log.print('iCloud: already set')
        else
          Log.success('set iCloud: on')
          app = app.update_service(Spaceship::Portal.app_service.icloud.on)
        end
```

Now if I go to [the spaceship developer docs here](https://github.com/fastlane/fastlane/blob/master/spaceship/docs/DeveloperPortal.md#app-services), the currently available services for the `Spaceship::Portal.app_service.` prefix does specify `icloud.(on|off)`. So I'm somewhat at a dead end on trying to figure out what to do next.

I do note that I'm still on fastlane 2.160 (I had to pin because of an earlier break). So I will try moving that to 2.163.

**Comment by bitce** [comment]
Hi @rickmanelius!

Would you be able to enable Support User access in the Settings of this app for us?

**Comment by rickmanelius** [comment]
@bitce Sure thing. Done!

**Comment by mjones-droid** [comment]
Hey @rickmanelius... For whatever reason I still can't access your app. Would you mind toggling support access off and on again? 

I did find one other [post with a similar error](https://github.com/fastlane/fastlane/issues/11800) but it was a bug that should have been resolved back in Fastlane 2.89.0...

**Comment by rickmanelius** [comment]
@mjones-droid Weird. I can see it turned off and I swear it was enabled. It took 3 attempts, but now it looks like it's set! Sorry about that.

**Comment by mjones-droid** [comment]
@rickmanelius No problem. Here are a few troubleshooting steps to try:

1.) It looks like the build you sent used version 1.5.3 or the step. Let's try it again with the newest version (1.5.4) to see if the issues persists. 

2.) If that doesn't work, try testing locally with a clean git clone at the Bitrise CLI. That should help us narrow down whether it's an issue with the step / project config or the environment. More information here: https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/ 

3.) It looks like you're using the old auto-provision step which authenticates with your apple id / password. It might be worth trying the newer step "iOS Auto Provision with App Store Connect API" to see if we get the same error there.

**Comment by rickmanelius** [comment]
Hi @mjones-droid. Wow! Thanks for the very quick turnaround on feedback 😅 Stepping through all 3 now and I'll report back.

I'll probably switch the order to 1 > 3 > 2. The only reason being is that I know there are some Bitrise.io steps that only run ifCI and I don't want to introduce dependency drift as a potential variation.

**Comment by rickmanelius** [comment]
Hi @mjones-droid. Here are initial updates:

1. Updating the legacy step to v1.5.4 resulted in the same error as per [build 3556](https://app.bitrise.io/build/0e586aadcd518f52#?tab=log)
2. The legacy step can't run locally because of [.IsCI](https://github.com/bitrise-io/bitrise-steplib/blob/master/steps/ios-auto-provision/1.5.4/step.yml#L73). The same is true for [the new step here](https://github.com/bitrise-io/bitrise-steplib/blob/master/steps/ios-auto-provision-appstoreconnect/0.1.1/step.yml#L32).
3. The new step `ios-auto-provision-appstoreconnect` was a little challenging to get setup, but we did it. The problem is we hit a very weird/frustrating bug. As a result of this step, our provisioning profiles get invalidated. We set these profiles to not just use the default, but we were approved for the contact card note entitlement. I watched the build and was refreshing the provisioning profile and it happened exactly when this step executed. I'll file an issue over there.

Net net. We will try to file an issue with `ios-auto-provision-appstoreconnect` so we can proceed with using this newer step. And then we can go from there.

**Comment by rickmanelius** [comment]
Alrighty. I [filed the issue](https://github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/issues/20) on the new `ios-auto-provision-appstoreconnect step`. It looks like it might be a syntax issue passing along the custom entitlements. More to come...

**Comment by rickmanelius** [comment]
Hi @mjones-droid. I don't know if you're able to nudge a response on the other issue queue. I think I identified a syntax error that should hopefully be easy to trace.

**Comment by mjones-droid** [comment]
Hey @rickmanelius! Sorry for the delayed response. I've filed a bug report and sent this to the dev's.

**Comment by rickmanelius** [comment]
@mjones-droid All good. I appreciate you 🙏🏻

**Comment by rickmanelius** [comment]
Closing as per the comment in the linked thread.
