### ISSUE TITLE
Don't work when try to work with mac devices

### ISSUE THREAD

**Issue by mackoj** [bitrise-steplib/steps-ios-auto-provision#140]
Hi @godrei,

I have an issue with auto provisioning we have mac in our deveices and auto provisioning crash on their ids.

This is what is called in order

- https://github.com/bitrise-steplib/steps-ios-auto-provision/blob/d8d3c3a55da353cae93c421bc7fc79976f4b1a41/lib/autoprovision/portal/device_client.rb#L43

- https://github.com/fastlane/fastlane/blob/2624a24407dee94f67d7e39b5651f9fdc41dcb00/spaceship/lib/spaceship/portal/device.rb#L145

- https://github.com/fastlane/fastlane/blob/2624a24407dee94f67d7e39b5651f9fdc41dcb00/spaceship/lib/spaceship/portal/device.rb#L158

- https://github.com/fastlane/fastlane/blob/2624a24407dee94f67d7e39b5651f9fdc41dcb00/spaceship/lib/spaceship/portal/portal_client.rb#L537

- https://github.com/fastlane/fastlane/blob/2624a24407dee94f67d7e39b5651f9fdc41dcb00/spaceship/lib/spaceship/portal/portal_client.rb#L542

But as you can see here if the device is a mac it will default to iPhone if mac parameter is not set.

Can you please provide a fix for this ?

**Comment by mjones-droid** [comment]
Hey @mackoj! I absolutely see what you're saying. The default value for 'mac' in the create method is false. Our create method in the iOS Auto Provision step doesn't include a parameter for mac, so it always defaults to creating an iPhone device. 

I'm filing a bug report with the dev's. Thanks for providing such a detailed issue!

**Comment by mackoj** [comment]
Thanks, I hope for @mjones-droid I hope for it to be fixed soon. With the new M1 hardware more people use mac devices 🤣 with auto-provision.

**Comment by mjones-droid** [comment]
Absolutely. I agree with with you there! :)

**Comment by mackoj** [comment]
Have you made any progress on a fix ?

**Comment by mjones-droid** [comment]
Howdy @mackoj! I just checked the status of the bug report and it looks like it's still being worked on.

**Comment by mackoj** [comment]
Hi where are you on this issue ? @mjones-droid

**Comment by mjones-droid** [comment]
Hi! Progress on this temporarily slowed while everyone was out on the holidays. It looks like it's planned for an upcoming sprint in the very near future at this point. As you predicted a growing number of our customers are now using Bitrise for MacOS. :)

**Comment by mackoj** [comment]
@mjones-droid the same issue affect his repo too https://github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect

**Comment by lpusok** [comment]
Hello @mackoj ,
We released a fix that prevents errors if using mac devices (https://github.com/bitrise-steplib/steps-ios-auto-provision/releases/tag/1.5.8). Mac devices are not supported yet but they do not cause crash.
Will close this specific issue.
