### ISSUE TITLE
Error in latest version 1.5.6: undefined method map' for nil:NilClass

### ISSUE THREAD

**Issue by MarshalGeazipp** [bitrise-steplib/steps-ios-auto-provision#143]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? _1.5.6_
- Is the issue reproducible with the latest version? _YES_
- Does the issue happen sporadically, or every time? _EVERY TIME_
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? _YES_

### Issue description

The step failed with exit code 1. It's an "undefined method" error in profile_client.rb:230
I'm pretty sure this bug was introduced in the latest version that was released today. Version 1.5.5 works fine!

### Bitrise info

- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _NO_
- Log: 

<details>
  <pre>
Matching project codesign identity with the uploaded certificates
using: Apple Development: ***
using: Apple Distribution: ***

Ensure test devices on Developer Portal
No test devices registered on Bitrise.

Ensure Provisioning Profiles on Developer Portal
checking app for target: **** (****) on developer portal
Push Notifications already enabled
Associated Domains already enabled
Data Protection: complete already set
ensure development profile for target: **** on developer portal

 Error:
undefined method `map' for nil:NilClass
Stacktrace (for debugging):
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise026350688/step_src/lib/autoprovision/portal/profile_client.rb:230:in `device_list_up_to_date?'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise026350688/step_src/lib/autoprovision/portal/profile_client.rb:108:in `ensure_manual_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise026350688/step_src/lib/autoprovision/portal/profile_client.rb:116:in `rescue in ensure_manual_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise026350688/step_src/lib/autoprovision/portal/profile_client.rb:102:in `ensure_manual_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise026350688/step_src/lib/autoprovision/profile_helper.rb:93:in `block in ensure_manual_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise026350688/step_src/lib/autoprovision/profile_helper.rb:81:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise026350688/step_src/lib/autoprovision/profile_helper.rb:81:in `ensure_manual_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise026350688/step_src/lib/autoprovision/profile_helper.rb:42:in `block in ensure_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise026350688/step_src/lib/autoprovision/profile_helper.rb:38:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise026350688/step_src/lib/autoprovision/profile_helper.rb:38:in `ensure_profiles'
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise026350688/step_src/step.rb:91:in `<main>'
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | ios-auto-provision (exit code: 1)                             | 2.2 min  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...github.com/bitrise-steplib/steps-ios-auto-provision/issues |
| Source: https://github.com/bitrise-steplib/steps-ios-auto-provision          |
+---+---------------------------------------------------------------+----------+
  </pre>
</details>

**Comment by lpusok** [comment]
Thanks @MarshalGeazipp,
Reverted to the previous version (released as 1.5.7) and will check what caused the problem.

**Comment by MarshalGeazipp** [comment]
Thank you @lpusok for your quick response! 👍

**Comment by lpusok** [comment]
@MarshalGeazipp released a new version (1.5.8) can you please check that it works  for you? This includes the changes indended to be made initially.

**Comment by MarshalGeazipp** [comment]
@lpusok yes, 1.5.8 works for me.
