### ISSUE TITLE
Error in uses_xcode_auto_codesigning when missing TargetAttributes

### ISSUE THREAD

**Issue by yonaskolb** [bitrise-steplib/steps-ios-auto-provision#21]
This is similar to the issue logged in #18 
It's crashing if `TargetAttributes` is nil or doesn't contain the target id

```
...
Error:
undefined method `[]' for nil:NilClass
Stacktrace (for debugging):
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise598287177/step_src/lib/autoprovision/project_helper.rb:56:in `uses_xcode_auto_codesigning?'
```

**Comment by godrei** [comment]
Hi @yonaskolb ,
we released a new version: [1.0.1](https://github.com/bitrise-steplib/steps-ios-auto-provision/releases/tag/1.0.1), which should fix this problem.
I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
