### ISSUE TITLE
Unable to retrieve tvOS app-store provisioning profile

### ISSUE THREAD

**Issue by wangqingzhouleo** [bitrise-steplib/steps-ios-auto-provision#36]
When managing tvOS provisioning profiles using auto provision step, it is unable to download app-store profile for tvOS target.

Here you can see it downloads correct development profile, but it cannot find app-store profile:
```
Ensure Provisioning Profiles on Developer Portal
checking xcode managed development profile for target: Axis_tvOS (co.massive.axis.demo) with 1 services on developer portal
downloading development profile: tvOS Team Provisioning Profile: co.massive.axis.demo
checking xcode managed development profile for target: Axis_tvOS_topshelf (co.massive.axis.demo.topshelf) with 1 services on developer portal
downloading development profile: tvOS Team Provisioning Profile: co.massive.axis.demo.topshelf
checking xcode managed app-store profile for target: Axis_tvOS (co.massive.axis.demo) with 1 services on developer portal
```

Then it throws an error:
```
Error:
Failed to find app-store Xcode managed provisioning profile for bundle id: co.massive.axis.demo.
```
However, all 6 profiles (app-store, app-store topshelf etc) are created and uploaded to Bitrise.

Also when I set `generate_profiles` to yes, it always generate iOS provision profiles. Is it possible to make this step generate tvOS profiles so that we don't need to upload profiles manually.

**Comment by bitce** [comment]
Hi @wangqingzhouleo ! Can you please send us a log file or URL to the build to be able to look into it? You can paste it here, or contact us on our on-site chat 🙂

**Comment by wangqingzhouleo** [comment]
[2662dc590d8327b9.log](https://github.com/bitrise-steplib/steps-ios-auto-provision/files/2292038/2662dc590d8327b9.log)
you could also find the URL to the build at [here](https://app.bitrise.io/build/2662dc590d8327b9)

**Comment by bitce** [comment]
Thanks! We'll look into it and get back to you as soon as possible!

**Comment by tamasbazs** [comment]
Hi @wangqingzhouleo,
Could you enable Support User Access to the app (you can find a guide here on how to do that: https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) , so our tooling team can look into the issue?

**Comment by wangqingzhouleo** [comment]
Hi @tamasbazs, Support User Access was already on. Are you not able to access the app?

**Comment by trapacska** [comment]
Hi @wangqingzhouleo !

We already have scheduled a check+fix card for your another issue. We'll notify you as soon as we've any progress about tvOS support.

**Comment by trapacska** [comment]
The new release is out with the fix, please let us know if you still encounter any issues with it.

https://github.com/bitrise-steplib/steps-ios-auto-provision/releases/1.2.1
