### ISSUE TITLE
1.2.0 build introduces issues for app extensions without profiles

### ISSUE THREAD

**Issue by mrrhysbutler** [bitrise-steplib/steps-ios-auto-provision#44]
Our app (automatically managed profiles) uses a Notification Extension, and the latest version will cause our build to fail.

Relevant part of log:
```
Ensure Provisioning Profiles on Developer Portal

checking xcode managed development profile for target: (com.[REDACTED]) with 2 services on developer portal
downloading development profile: iOS Team Provisioning Profile: com.[REDACTED]
checking xcode managed development profile for target: Notification Service (com.[REDACTED].notification-service) with 1 services on developer portal

Error:
Failed to find development Xcode managed provisioning profile for bundle id: com.[REDACTED].notification-service.
```

Rolling back to 1.1.5 will prevent the issue occurring.

My best guess at the problem is that our extension does not use its own provisioning profile, it uses the wildcard profile, and because of this the step has no profile to find and fails. In my experience it is pretty common for the notification extension to be assigned the wildcard profile, at least for develop build.

We will use 1.1.5 for now but hopefully this is something that can be addressed in a future build, or am I misreading the situation?

**Comment by bitce** [comment]
Hi @mrrhysbutler ,

Thanks for contacting us about this and sorry for the inconvenience this may have caused! Could you please send us a URL to a build where it failed on the latest version due to this?

**Comment by tibiiii** [comment]
Same issue happened for us. 1.2.0 fails with not finding matching provisioning profile. 1.1.5 works fine.
Failing build: https://app.bitrise.io/build/6cc760595c9785ce

**Comment by godrei** [comment]
Hi @tibiiii and @mrrhysbutler ,
may i ask you guys to send a success build urls, which uses the step version 1.1.5?

**Comment by svyatogor** [comment]
Same problem here.

**Comment by anniewey** [comment]
+1 on 1.2.3

**Comment by simonmitchell** [comment]
Same using 1.3.0... c'mon guys! Auto-provisioning is such a great step, and I'm sure you're the biggest expert on code signing out there... sure you can fix this!

**Comment by bitce** [comment]
Hi guys! We've found that this error message can be caused by numerous root issues, can you please contact us at our on-site chat or via e-mail at letsconnect@bitrise.io about these issues you've been experiencing?

**Comment by glennposadas** [comment]
Ha! I'm experiencing this error right now. Sent you Bitrise team a chat. Thank you!

**Comment by lpusok** [comment]
Hello @mrrhysbutler, @tibiiii, @svyatogor, @blau2, @anniewey, @simonmitchell, @glennposadas!

Please upgrade to the _iOS Auto Provision with App Store Connect API Step_  (https://devcenter.bitrise.io/getting-started/connecting-to-services/bitrise-steps-and-their-authentication-methods/#ios-auto-provision-with-app-store-connect-api-step).
This requires API Key authentication (https://devcenter.bitrise.io/getting-started/connecting-to-services/setting-up-connection-to-an-apple-service-with-api-key/).

In case you are using Enterprise distribution as a member of Apple Developer Enterprise Program,  you can not upgrade as API Keys are not provided by Apple. In this case please reopen this issue or contact our Support for assistance.
