### ISSUE TITLE
Wrong Distribution type selected

### ISSUE THREAD

**Issue by wqz-leo** [bitrise-steplib/steps-ios-auto-provision#48]
Version: 1.2.2
I'm using `app-store` distribution type in the configuration, but when trying to upload app to App Store, **xcode-archive** failed with error:
```
Provisioning profile "Bitrise development - (co.massive.axis.demo)" doesn't support the Access WiFi Information capability.
```
It is using development profile rather than app-store profile.

However, I tried with version 1.2.0 and  **xcode-archive** did use the correct distribution type.
Please find attached logs for 1.2.0 and 1.2.2
[1.2.0.log](https://github.com/bitrise-steplib/steps-ios-auto-provision/files/2661630/1.2.0.log)
[1.2.2.log](https://github.com/bitrise-steplib/steps-ios-auto-provision/files/2661631/1.2.2.log)

**Comment by wangqingzhouleo** [comment]
And this step does not auto-regenerate profiles even if profile is invalid.
The build succeed and profiles are generated again after I delete profiles from the portal manually.

**Comment by fehersanyi-bitrise** [comment]
Hello @wangqingzhouleo !

Could you check the profile on the developer portal if it is set up properly?
`ensure app-store profile for target: Axis_iOS on developer portal`

and if you use auto provisioning, then you don't need the certificates and profile downloader step.

these could also be the cause: `Provisioning profile "Bitrise app-store - (co.massive.axis.demo)" doesn't support the Access WiFi Information capability.`

`Provisioning profile "Bitrise app-store - (co.massive.axis.demo)" doesn't include the com.apple.developer.networking.wifi-info entitlement.`
