### ISSUE TITLE
Revoking push certificates

### ISSUE THREAD

**Issue by an-zuper** [bitrise-steplib/steps-ios-auto-provision#5]
When I added this step instead "Certificate and profile installer" it revoked both my push certificates. Build passes and everything was ok, but app can't receive push notifications.
On Apple dev portal certificates are missing

**Comment by viktorbenei** [comment]
Thanks for reporting @an-zuper !

Can you please copy paste the build's bitrise.io URL? We'd need the full logs for debugging. If possible it'd also help if you could enable Support Access for the related app (you can do that on the Settings tab of the app on bitrise.io).

**Comment by godrei** [comment]
Hi @an-zuper ,
we released a [new version](https://github.com/bitrise-steplib/steps-ios-auto-provision/releases/tag/0.9.3) which should fix this issue. Please update the step and let us know if you have any issue with the new version.
