### ISSUE TITLE
failed to resolve bundle id (${CUSTOM_BUNDLE_ID})

### ISSUE THREAD

**Issue by telenc** [bitrise-steplib/steps-ios-auto-provision#53]
Hello,

I have a problem
I have a XCConfig File with inside 
`CUSTOM_BUNDLE_ID = company.bundle.info`

But I have this error
<img width="1309" alt="capture d ecran 2018-12-26 a 12 03 04" src="https://user-images.githubusercontent.com/5463621/50444014-40047b00-0906-11e9-82b8-1e5416b5766f.png">

thanks

**Comment by telenc** [comment]
Error in info.plist SORRY

**Comment by fehersanyi-bitrise** [comment]
Hy! no problem, we are glad you could solve it!
