### ISSUE TITLE
Test devices are not being added to new provisioning profile on 1.2.3

### ISSUE THREAD

**Issue by Javi** [bitrise-steplib/steps-ios-auto-provision#54]
I added a new test device on Bitrise (and the Apple Dev Portal just to be sure), so the build says all devices are already registered with nothing to do. "generate_profiles" is also set to `yes` but then no profiles seem to be created, instead downloading one that does not include the new test device, without any apparent errors. I can't try any previous versions to 1.2.3 due to issue #49 (regarding `adhoc` and `fastlane`) to see if this might be working previously.

**Comment by vdimitrovv** [comment]
@Javi this could be related to the adhoc bug that was introduced in 2.111.0. If that's the case then the https://github.com/bitrise-steplib/steps-ios-auto-provision/pull/52 PR should resolve it.

**Comment by godrei** [comment]
Hi @Javi , we have released a new version: [1.3.0](
https://github.com/bitrise-steplib/steps-ios-auto-provision/releases/tag/1.3.0), could you please check if it solves your issue?

**Comment by Javi** [comment]
Still doesn't seem to work, can you repro it?

**Comment by fehersanyi-bitrise** [comment]
Hello there!

We realised that it is not working as intended, and reviewing the new version.
until then the workaround is to delete the bitrise managed profiles from the dev portal when a new UDID is added, so the step will generate a new profile that includes the test device.

**Comment by Alex-Mason-RocketInsights** [comment]
Has this been fixed? I am working with a client and do not have access to the Apple Developer portal and a new device has been added.

**Comment by fehersanyi-bitrise** [comment]
Hy @Alex-Mason-RocketInsights , there was a new release 1.3.1 24 days ago, did you check it with that one?

**Comment by Alex-Mason-RocketInsights** [comment]
Yes I did, however it does not appear to A) Create a profile that has Push Notifications Capability or B) Add said profile to the export options plist. I opened a full issue here: https://discuss.bitrise.io/t/ios-autoprovision-does-not-work-for-provisioning-profile-that-requires-push-notifications-capability/8477

**Comment by ethan021021** [comment]
Would love to see a fix for this, just tried to add a test users device UDID to the apple developer portal and the Bitrise test device portal and the step said it found the UDID registered in both. But I had to manually delete my provisioning files on my Mac so Xcode could regenerate them. After I did that the step started working again.

**Comment by bitce** [comment]
Hi @ethan021021!

This problem shouldn't really be present anymore. Can you please contact us on-site with your builds details so we can investigate?

**Comment by kzietek** [comment]
Hi!

I'm using "iOS Auto Provision" v1.5.2 and the problem still persists. I'm using a workaround to regenerate the team provisioning profile:
- Archive selected target locally (probably optional if you already have an archive)
- Make an ipa from archived target. Use automatic signing so XCode changes something invisible on Apple's side.

Probably to fix this permanently it is needed to alter the "XCode Archive & Export for iOS" step.

**Comment by bitce** [comment]
Hi @kzietek, can you please send us a report about this so we can investigate? 

What we'd need is:

- A URL to a build where this issue is happening
- A UDID for a device that is registered on Bitrise (we'd need a screenshot)
- Support Access for the app which you can turn on in the Settings.

Thanks!
