### ISSUE TITLE
Error in certificate_common_name

### ISSUE THREAD

**Issue by peterwarbo** [bitrise-steplib/steps-ios-auto-provision#58]
I'm getting the error below. I have uploaded my distribution certificate.

Error:
undefined method `subject' for nil:NilClass
Stacktrace (for debugging):
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise883594639/step_src/lib/autoprovision/utils.rb:2:in `certificate_common_name'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise883594639/step_src/lib/autoprovision/utils.rb:10:in `certificate_name_and_serial'

**Comment by fehersanyi-bitrise** [comment]
Hello there!

Could you please provide us the url of this failed build, so we can check the full logs?

**Comment by fannt** [comment]
Same error here. v1.3.1
build url: `https://app.bitrise.io/build/3fbb82ba4c731527`

**Comment by fehersanyi-bitrise** [comment]
Hy @fannt Could you please enable support user on the settings tab, I would like to check out this config, maybe there is an issue with the certificate 🤔

**Comment by fannt** [comment]
Yep, there were some problems with certificates, although fixed with `codesigndoc`. Thanks though.

**Comment by amadeu01** [comment]
Same error here
