### ISSUE TITLE
Step failing on 1.3.1 but working on 1.3.0 and 1.2.3

### ISSUE THREAD

**Issue by tadija** [bitrise-steplib/steps-ios-auto-provision#63]
Hi, I wanted to report a problem with the latest version of this step. It's reproducable each time:

On step version 1.3.1 there is this error:

```
Failed to find development Xcode managed provisioning profile for bundle id: ...
Please open your project in your local Xcode and generate and ipa file
with the desired distribution type and by using Xcode managed codesigning.
This will create / refresh the desired managed profiles.
```

On step versions 1.3.0 and 1.2.3 everything works normally without that error and app is correctly signed.

Any ideas?

**Comment by clementleroy** [comment]
Did you add [2FA on your Apple ID](https://developer.apple.com/support/account/authentication/) ?

**Comment by tadija** [comment]
Yes, I also reconnected Apple Developer account with 2FA on Bitrise in order to make it work, and created the application specific password which is used in "Deploy to iTunes Connect" step.

Does "iOS Auto Provision" step need any other changes related to 2FA? I didn't notice any new settings related to that.

**Comment by dmitrysimkin** [comment]
Still happened to me on 1.5.2. I followed the instructions and created ipa using Xcode and it helped. But I'm wondering why it actually helps. It says `This will create / refresh the desired managed profiles.` but I haven't noticed any changes on dev portal.

**Comment by Roland-Bak** [comment]
Hi there everyone!
Just wanted to let you know that we have a new and shiny step called iOS Auto Provision with App Store Connect API, which is a new and improved auto provisioning step 🙂
Try using it and let us know if the issue still persists!
