### ISSUE TITLE
bundle install failed with Xcode 10.2.x Stack

### ISSUE THREAD

**Issue by stoffy** [bitrise-steplib/steps-ios-auto-provision#64]
Hi!
Since we updated to Swift 5 and changed the default stack to Xcode 10.2.x on macOS10.14 the workflow `ios-auto-provision` fails:

id: ios-auto-provision                                                       
version: 1.3.1                                                               
collection: https://github.com/bitrise-io/bitrise-steplib.git                
toolkit: bash                                                                
time: 2019-05-20T15:00:53Z 

`$ bundle install
rbenv: version 2.5.1 is not installed (set by /Users/vagrant/git/.ruby-version)
bundle install failed`

Any idea what is wrong?
Thank you in advanced.

**Comment by bitce** [comment]
Hi @stoffy!

Seems to be the same issue as this one: https://github.com/bitrise-steplib/steps-cocoapods-install/issues/41
