### ISSUE TITLE
Install certificate error with complex password

### ISSUE THREAD

**Issue by OrWest** [bitrise-steplib/steps-ios-auto-provision#73]
Hello.
I uploaded the certificate (p12) with complex password: 

> DKQt)VF5@0HK\\GG{-\3

On Bitrise step it was failed with error:

>Install certificates
sh: -c: line 0: syntax error near unexpected token `)'
sh: -c: line 0: `security import "/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/Certrificate_0.p12" -k "/Users/vagrant/Library/Keychains/login.keychain" -P DKQt)VF5@0HK\\GG{-\3 -A'

>Error:
security import "/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/Certrificate_0.p12" -k "/Users/vagrant/Library/Keychains/login.keychain" -P DKQt)VF5@0HK\\GG{-\3 -A failed, out: 

>Stacktrace (for debugging):
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise055551208/step_src/lib/autoprovision/keychain_helper.rb:50:in `import_certificate'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise055551208/step_src/lib/autoprovision/keychain_helper.rb:33:in `block in install_certificates'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise055551208/step_src/lib/autoprovision/keychain_helper.rb:32:in `each'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise055551208/step_src/lib/autoprovision/keychain_helper.rb:32:in `install_certificates'
/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise055551208/step_src/step.rb:136:in `<main>'

Seems password in command should be quoted to prevent this issue.

**Comment by CalQL8ed-K-OS** [comment]
I can corroborate this, I had a PW for my p12 that included a double quote `"` character, when I removed that cert and replaced with a p12 holding the same cert, but with a simply alphanumeric password, it resolved the issue.

**Comment by sethdeckard** [comment]
I ran into the same issue since I used a PW generator to generate a strong password and it contained the following specials: `<-=?'#;{$>(\%*:`

**Comment by bitce** [comment]
Hi guys! 

Sorry for our silence on this. The team is aware of the problem and has a related task to fix this. We'll make sure to update this thread once it's done! 🙂

**Comment by michaelrccurtis** [comment]
This issue appears to still be present - we've fixed by using a purely alphanumeric password but it would be great to see this addressed. We also got this error: https://github.com/bitrise-steplib/steps-ios-auto-provision/issues/125, when using a slightly different password (possibly with a space inside, which a glance at the code might mean the way the password is injected into the cli command is broken).

**Comment by mjones-droid** [comment]
Hey Michael. I'm sorry you're still experiencing issues with this. 

Can you enable support access on your app and send us a link to a recent build with these issues? Thanks!

**Comment by roajeremy** [comment]
Hello, any solution to this?

```
Install certificates
$ security import "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/Certrificate_2.p12" -k '/Users/vagrant/Library/Keychains/login.keychain-db' -P "****" -A
security: SecKeychainItemImport: MAC verification failed during PKCS12 import (wrong password?)
Error:
security import "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/Certrificate_2.p12" -k '/Users/vagrant/Library/Keychains/login.keychain-db' -P "****" -A failed, out: 
Stacktrace (for debugging):
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/lib/autoprovision/keychain_helper.rb:54:in `import_certificate'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/lib/autoprovision/keychain_helper.rb:33:in `block in install_certificates'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/lib/autoprovision/keychain_helper.rb:32:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/lib/autoprovision/keychain_helper.rb:32:in `install_certificates'
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/step.rb:137:in `<main>'
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | ios-auto-provision@1.5 (exit code: 1)                         | 1.9 min  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...github.com/bitrise-steplib/steps-ios-auto-provision/issues |
| Source: https://github.com/bitrise-steplib/steps-ios-auto-provision          |
+---+---------------------------------------------------------------+----------+
```

https://app.bitrise.io/build/8f25eefab52bb46d#?tab=log

this is my build failed

**Comment by thinguyenbit** [comment]
> Hello, any solution to this?
> 
> ```
> Install certificates
> $ security import "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/Certrificate_2.p12" -k '/Users/vagrant/Library/Keychains/login.keychain-db' -P "****" -A
> security: SecKeychainItemImport: MAC verification failed during PKCS12 import (wrong password?)
> Error:
> security import "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/Certrificate_2.p12" -k '/Users/vagrant/Library/Keychains/login.keychain-db' -P "****" -A failed, out: 
> Stacktrace (for debugging):
> /private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/lib/autoprovision/keychain_helper.rb:54:in `import_certificate'
> /private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/lib/autoprovision/keychain_helper.rb:33:in `block in install_certificates'
> /private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/lib/autoprovision/keychain_helper.rb:32:in `each'
> /private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/lib/autoprovision/keychain_helper.rb:32:in `install_certificates'
> /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/step.rb:137:in `<main>'
> |                                                                              |
> +---+---------------------------------------------------------------+----------+
> | x | ios-auto-provision@1.5 (exit code: 1)                         | 1.9 min  |
> +---+---------------------------------------------------------------+----------+
> | Issue tracker: ...github.com/bitrise-steplib/steps-ios-auto-provision/issues |
> | Source: https://github.com/bitrise-steplib/steps-ios-auto-provision          |
> +---+---------------------------------------------------------------+----------+
> ```
> 
> https://app.bitrise.io/build/8f25eefab52bb46d#?tab=log
> 
> this is my build failed

Can you please enable support access? 

Thi

**Comment by roajeremy** [comment]
> > Hello, any solution to this?
> > ```
> > Install certificates
> > $ security import "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/Certrificate_2.p12" -k '/Users/vagrant/Library/Keychains/login.keychain-db' -P "****" -A
> > security: SecKeychainItemImport: MAC verification failed during PKCS12 import (wrong password?)
> > Error:
> > security import "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/Certrificate_2.p12" -k '/Users/vagrant/Library/Keychains/login.keychain-db' -P "****" -A failed, out: 
> > Stacktrace (for debugging):
> > /private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/lib/autoprovision/keychain_helper.rb:54:in `import_certificate'
> > /private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/lib/autoprovision/keychain_helper.rb:33:in `block in install_certificates'
> > /private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/lib/autoprovision/keychain_helper.rb:32:in `each'
> > /private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/lib/autoprovision/keychain_helper.rb:32:in `install_certificates'
> > /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/step.rb:137:in `<main>'
> > |                                                                              |
> > +---+---------------------------------------------------------------+----------+
> > | x | ios-auto-provision@1.5 (exit code: 1)                         | 1.9 min  |
> > +---+---------------------------------------------------------------+----------+
> > | Issue tracker: ...github.com/bitrise-steplib/steps-ios-auto-provision/issues |
> > | Source: https://github.com/bitrise-steplib/steps-ios-auto-provision          |
> > +---+---------------------------------------------------------------+----------+
> > ```
> > 
> > 
> > https://app.bitrise.io/build/8f25eefab52bb46d#?tab=log
> > this is my build failed
> 
> Can you please enable support access?
> 
> Thi

Done!

**Comment by thinguyenbit** [comment]
> > > Hello, any solution to this?
> > > ```
> > > Install certificates
> > > $ security import "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/Certrificate_2.p12" -k '/Users/vagrant/Library/Keychains/login.keychain-db' -P "****" -A
> > > security: SecKeychainItemImport: MAC verification failed during PKCS12 import (wrong password?)
> > > Error:
> > > security import "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/Certrificate_2.p12" -k '/Users/vagrant/Library/Keychains/login.keychain-db' -P "****" -A failed, out: 
> > > Stacktrace (for debugging):
> > > /private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/lib/autoprovision/keychain_helper.rb:54:in `import_certificate'
> > > /private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/lib/autoprovision/keychain_helper.rb:33:in `block in install_certificates'
> > > /private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/lib/autoprovision/keychain_helper.rb:32:in `each'
> > > /private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/lib/autoprovision/keychain_helper.rb:32:in `install_certificates'
> > > /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise199243010/step_src/step.rb:137:in `<main>'
> > > |                                                                              |
> > > +---+---------------------------------------------------------------+----------+
> > > | x | ios-auto-provision@1.5 (exit code: 1)                         | 1.9 min  |
> > > +---+---------------------------------------------------------------+----------+
> > > | Issue tracker: ...github.com/bitrise-steplib/steps-ios-auto-provision/issues |
> > > | Source: https://github.com/bitrise-steplib/steps-ios-auto-provision          |
> > > +---+---------------------------------------------------------------+----------+
> > > ```
> > > 
> > > 
> > > https://app.bitrise.io/build/8f25eefab52bb46d#?tab=log
> > > this is my build failed
> > 
> > 
> > Can you please enable support access?
> > Thi
> 
> Done!

Can you try removing the certificates under the codesigning tab, generating new ones and uploading them back?

Thi
