### ISSUE TITLE
Step fails when Apple distribution certificate is added in Bitrise (Xcode 11)

### ISSUE THREAD

**Issue by SebastianOsinski** [bitrise-steplib/steps-ios-auto-provision#85]
We just set up new project which uses Xcode 11. Xcode 11 supports new type of certificate - Apple Distribution certficates. When such certificate is added to Code Signing Identities, this step fails, even when given workflow relies on different certificate (e.g. enterprise distribution certificate):

```
Downloading Certificates
Error:
undefined method `subject' for nil:NilClass
Stacktrace (for debugging):
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise094332727/step_src/lib/autoprovision/utils.rb:2:in `certificate_common_name'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise094332727/step_src/lib/autoprovision/utils.rb:10:in `certificate_name_and_serial'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise094332727/step_src/lib/autoprovision/certificate_helper.rb:31:in `block (2 levels) in download_and_identify'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise094332727/step_src/lib/autoprovision/certificate_helper.rb:30:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise094332727/step_src/lib/autoprovision/certificate_helper.rb:30:in `block in download_and_identify'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise094332727/step_src/lib/autoprovision/certificate_helper.rb:21:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise094332727/step_src/lib/autoprovision/certificate_helper.rb:21:in `each_with_index'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise094332727/step_src/lib/autoprovision/certificate_helper.rb:21:in `download_and_identify'
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise094332727/step_src/step.rb:37:in `<main>'
```

**Comment by maxlapides** [comment]
I also had an issue with the Apple Distribution certificates. I'm not sure what was going on. I ended up manually creating an iOS Distribution certificate on developer.apple.com and manually uploading it to Bitrise.

**Comment by bitce** [comment]
Hey everyone!

These issues should be solved since https://github.com/bitrise-steplib/steps-ios-auto-provision/pull/87 - so above step version 1.4.0 you shouldn't experience this problem, but please let us know what you do experience!

**Comment by iRaru** [comment]
With version 1.4.1 I still have error with Xcode 11 machines (I tried different situations but without success -- only iPhone certificates, only new Apple certificates, both of them)

Downloading Certificates
4 certificate files downloaded, 4 distinct codesign identities included

Identify Certificates on Developer Portal
iOS Distribution certificate found: iPhone Distribution: XXX [327...]
iOS Development certificate found: iPhone Developer: XXX [287...]
Development certificate found: Apple Development: XXX [571...]
Distribution certificate found: Apple Distribution: XXX [537...]

Analyzing project
target codesign identity: Apple Development does not match to the already registered codesign identity: iPhone Developer

Error:
failed to determine project code sign identity
Stacktrace (for debugging):
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise201064441/step_src/lib/autoprovision/project_helper.rb:105:in `project_codesign_identity'
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise201064441/step_src/step.rb:44:in `<main>'

**Comment by sxua** [comment]
@iRaru you should change `CODE_SIGN_IDENTITY` setting in your project to `Apple Developer` to resolve this

**Comment by nickprkins** [comment]
@sxua I've tried what you've stated and it doesn't work. I change it to the exact identity and it still gives that error

**Comment by iRaru** [comment]
> @iRaru you should change `CODE_SIGN_IDENTITY` setting in your project to `Apple Developer` to resolve this

@sxua, thanks this fixed my problem ;)

**Comment by johannwerner** [comment]
I have Apple Development. Is that the same as Apple Developer?

**Comment by vassily-fr** [comment]
> I have Apple Development. Is that the same as Apple Developer?

I tried both and : 
iOS Developer -> bitrise auto-privisionning works
Apple Developer -> bitrise autoprovisionning Fails

Don't really understand why (or what is the differences)

**Comment by bitce** [comment]
Hi @vassily-fr, if you send us some example build, we might be able to tell, for instance you may be using an Xcode version lower than 11.0, that would explain the newer certificate not working yet.
