### ISSUE TITLE
Fails with private Swift Package 

### ISSUE THREAD

**Issue by Sn0wfreezeDev** [bitrise-steplib/steps-ios-auto-provision#89]
In my current setup I am using a Swift Package which is hosted privately on GitHub. I use another public Swift Package as well. When the step is running it fails when it tries to resolve the packages. 

The following output is shown:
```
Analyzing project
xcodebuild: error: Could not resolve package dependencies:
  Authentication failed because no credentials were provided.
Error:
xcodebuild -showBuildSettings -project "/Users/vagrant/git/WatchSonos.xcodeproj" -target "WatchSonos" -configuration "Release" failed, out: Resolve Package Graph
Fetching https://github.com/ApolloZhu/swift_qrcodejs.git
Fetching https://github.com/Sn0wfreezeDev/private_package.git
Stacktrace (for debugging):
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise043985305/step_src/lib/autoprovision/project_helper.rb:405:in `xcodebuild_target_build_settings'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise043985305/step_src/lib/autoprovision/project_helper.rb:325:in `target_codesign_identity'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise043985305/step_src/lib/autoprovision/project_helper.rb:83:in `block in project_codesign_identity'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise043985305/step_src/lib/autoprovision/project_helper.rb:80:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise043985305/step_src/lib/autoprovision/project_helper.rb:80:in `project_codesign_identity'
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise043985305/step_src/step.rb:44:in `<main>'
```

I use a Bitrise SSH Key that has been added manually to my GitHub, but the Swift Packages use https for authentication which may be the issue, why it fails here. 
Currently I have not found a method to add https authentication for this. 

Kind regards 
Alex

**Comment by bitce** [comment]
Hi @Sn0wfreezeDev! 

Sorry for the delay. Is it possible that you were using a slightly outdated version of the step here? This should have been fixed about a week before you raised this here https://github.com/bitrise-io/bitrise-steplib/pull/2147

**Comment by ikait** [comment]
I have the same problem with 1.4.2. Is there a way to solve this?

**Comment by bitce** [comment]
Hi @ikait,

Please submit a complete issue report to us, either in a thread or contact us directly!

**Comment by erfanandesta1373** [comment]
Any update on this?

**Comment by Roland-Bak** [comment]
Hello @erfanandesta1373 👋

Could you submit a ticket to us with more information (preferably with a build URL and Support Access Enabled for your build)? You can do so by either going to [https://support.bitrise.io/hc/en-us](https://support.bitrise.io) or by sending us an email at support@bitrise.io 🙂
