### ISSUE TITLE
Issue with missing project_path and scheme

### ISSUE THREAD

**Issue by Zaxist** [bitrise-steplib/steps-ios-auto-provision#91]
Hi I'm having an issue with this step where the project_path is missing. If I manually specify the project_path instead of leaving as env variable like: 
```/Users/vagrant/git```
Then it moves on to telling me that scheme is missing.

My workflow looks like:
Activate SSH key (RSA private key)
Git Clone Repository
Node Version Manager (NVM)
Run npm command
Ionic prepare
Script that runs ```cordova platform add ios ```
Cordova prepare
iOS Auto Provision

Is there something I am doing wrong here or this a possible bug? Can't find any information on this problem and wasn't sure where else to ask.

**Comment by bitce** [comment]
Hi @Zaxist, 

`/Users/vagrant/git` is the location your repository gets cloned to, you'd have to provide the path relative to that 🙂

**Comment by lewisvgd** [comment]
There is an issue here. Following the documentation here:
https://devcenter.bitrise.io/code-signing/ios-code-signing/ionic-cordova-code-signing/

Step 3 should require you to manually specify both the Xcode project and Scheme name (or this should be exposed as a variable in the cordova prepare step)

Note, the correct path is /Users/vagrant/git/platforms/ios/<project_name>.xcworkspace

Also worth noting you do need to set the Development team to $BITRISE_DEVELOPER_TEAM,
Code Signing Identity $BITRISE_DEVELOPMENT_CODESIGN_IDENTITY, Provisioning Profile to $BITRISE_DEVELOPMENT_PROFILE in the step Generate cordova build configuration

These are exposed during the auto provision step but do not show as outputs.
